services:

    db:
      image: postgres
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=postgres
      ports:
        - "5432:5432"

    db_init:
      image: postgres
      volumes:
        - ./book.dump:/db.dump
      environment:
        - PGPASSWORD=admin
      command: pg_restore -h db --no-owner --no-privileges -d postgres -U admin db.dump
      depends_on:
        db:
          condition: service_started
        
