services:

    db:
      image: postgres
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=postgres
      ports:
        - "5432:5432"
      shm_size: 1g
    command: |
        postgres
          -c shared_preload_libraries=pg_stat_statements
          -c pg_stat_statements.track=all
          -c max_connections=200
          -c shared_buffers=256MB
          -c effective_cache_size=8GB
          -c work_mem=16MB
          -c maintenance_work_mem=128MB
          -c min_wal_size=128MB
          -c max_wal_size=4GB
          -c checkpoint_completion_target=0.9
          -c wal_buffers=16MB
          -c default_statistics_target=100
    db_init:
      image: postgres
      volumes:
        - ./book.dump:/db.dump
      environment:
        - PGPASSWORD=admin
      command: pg_restore -h db --no-owner --no-privileges -d postgres -U admin db.dump
      depends_on:
        db:
          condition: service_started
      restart: on-failure
        
